### ISSUE TITLE
Out file location customization

### ISSUE THREAD

**Issue by SleepyTeaDrinker** [bap37/ParentPops#12]
From #11 

"set up a new output directory location toggle"
A new (optional) key in the command line that points to where the outputs should be stored. Right now the "output" directory is always created relative to the directory that the command is launched from. I've been informed that certain places don't allow write privileges where the code is stored, so this may need to be changed. Ideally this would take the form of an optional command line argument, "--OUTDIR", that specifies where the output directory should go.

**Comment by bap37** [comment]
Thank you!
